<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RSS_Feeds.Core\RSS_Feeds.Core.csproj" />
    <ProjectReference Include="..\RSS_Feeds.Data\RSS_Feeds.Data.csproj" />
  </ItemGroup>

</Project>
